---
title: "TT 12.06.20 AA achievements"
author: "AnaVoron"
date: "6/12/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
# calling the packages 

x <- c("tidyverse","readr","knitr","here")

lapply(x,require,character.only = T)
```

``` {r data}
# getting the data

firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')

```

``` {r preparing the dataframe}
# preparing our dataframe

firsts_gender1 <- firsts %>% mutate(decades = cut(year, breaks = seq(1730, 2020, by = 10), right = F, dig.lab = 4))

firsts_gender1 <- firsts_gender1 %>% mutate(gender = fct_recode(gender, "m"= "African-American Firsts", 
                                                                "f"= "Female African American Firsts"),
                                            decades = fct_recode(decades, "1730s"= "[1730,1740)", 
                                              "1750s"= "[1750,1760)",
                                              "1760s"= "[1760,1770)",
                                              "1770s"= "[1770,1780)",
                                              "1780s"= "[1780,1790)",
                                              "1790s"= "[1790,1800)",
                                              "1800s"= "[1800,1810)",
                                              "1810s"= "[1810,1820)",
                                              "1820s"= "[1820,1830)",
                                              "1830s"= "[1830,1840)",
                                              "1840s"= "[1840,1850)",
                                              "1850s"= "[1850,1860)",
                                              "1860s"= "[1860,1870)",
                                              "1870s"= "[1870,1880)",
                                              "1880s"= "[1880,1890)",
                                              "1890s"= "[1890,1900)",
                                              "1900s"= "[1900,1910)",
                                              "1910s"= "[1910,1920)",
                                              "1920s"= "[1920,1930)",
                                              "1930s"= "[1930,1940)",
                                              "1940s"= "[1940,1950)",
                                              "1950s"= "[1950,1960)",
                                              "1960s"= "[1960,1970)",
                                              "1970s"= "[1970,1980)",
                                              "1980s"= "[1980,1990)",
                                              "1990s"= "[1990,2000)",
                                              "2000s"= "[2000,2010)",
                                              "2010s"= "[2010,2020)"))

firsts_gender1 <- firsts_gender1 %>% count(gender,decades) %>%
    group_by(decades) %>% mutate(total = sum(n)) %>% ungroup()

```

``` {r plot}
# making the plot

firsts_gender1_graph<-ggplot(firsts_gender1, aes(x = decades, y = ifelse(gender == "m",
                                                                           yes = -n, no = n), fill = gender)) +
  geom_col() + coord_flip() + geom_hline(yintercept = 0, linetype = 1, colour = "white") +
  labs(title = "First achievements of African-American men and women",
       x = element_blank(),
       y = element_blank()) +
  scale_y_continuous(limits = c(-60,60),
                     breaks = c(-60, -20, -40, 0, 20, 40, 60),
                     labels = c("60", "20", "40", "0", "20", "40", "60")
                     ) +
  theme(plot.background = element_rect(fill = "#003f5c"),
        panel.background = element_rect(fill = "#003f5c",
                                        colour = "#003f5c",
                                        size = 0.5, linetype = "solid"
                                        ),
        legend.background = element_rect(fill="#003f5c", 
                                         size=0.5, linetype="solid"),
        panel.grid.major.y = element_line(size = 0.5, linetype = 'solid', colour = "grey"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_text(colour = "white"),
        axis.text.x = element_text(colour = "white"),
        axis.line.x = element_line(colour = "white"),
        plot.title = element_text(size = 20),
        text = element_text(size = 10, colour = "white"),
        legend.position = "top"
        ) +
  scale_fill_manual(values = c("#ff6361","#ffa600"),
                    name = element_blank(),
                    labels = c("Male", "Female")) +
  annotate(
    geom = "text", x = 4.5, y = 5, label = "First published author: Jupiter Hammon", 
           hjust = "left", colour = "white", size = 3.5
    ) +
  annotate(
    geom = "curve", x = 4.2, y = 5, xend = 2, yend = 1.4, 
    curvature = -.3, arrow = arrow(length = unit(2, "mm")), colour = "white", size = 0.5
    ) + 
  annotate(
    geom = "text", x = 3.5, y = -45, label = "First elected to public office: Wentworth Cheswell", 
           hjust = "left", colour = "white", size = 3.5
    ) +
  annotate(
    geom = "curve", x = 3, y = -12, xend = 2, yend = -2, 
    curvature = .1, arrow = arrow(length = unit(2, "mm")), colour = "white", size = 0.5
    ) +
  geom_rect(
    xmin = -.1,xmax = 1.5, ymin = -1, ymax = 1, fill = "grey"
    ) +
  annotate(
    geom = "text", x = 1.5, y = -30, label = "First free community: Fort Mose", 
           hjust = "left", colour = "white", size = 3.5
    ) +
  annotate(
    geom = "curve", x = 1.2, y = -8, xend = 1, yend = -1.4, 
    curvature = .2, arrow = arrow(length = unit(2, "mm")), colour = "white", size = 0.5
    ) +
  annotate(
    geom = "text", x = 22.5, y = 25, label = "Women's liberation movement", 
           hjust = "left", colour = "white", size = 3.5
    ) +
  annotate(
    geom = "curve", x = 22.5, y = 25, xend = 23, yend = 17, 
    curvature = .1, arrow = arrow(length = unit(2, "mm")), colour = "white", size = 0.5
    ) +
  annotate(
    geom = "text", x = 19.5, y = -50, label = "Civil Rights Act 1964", 
           hjust = "left", colour = "white", size = 3.5
    ) +
  annotate(
    geom = "curve", x = 19.5, y = -50, xend = 22, yend = -58, 
           curvature = -.5, arrow = arrow(length = unit(2, "mm")), colour = "white", size = 0.5
    ) +
  annotate(
    geom = "text", x = 11.5, y = -40, label = "Civil Rights Act 1866", 
           hjust = "left", colour = "white", size = 3.5
    ) +
  annotate(
    geom = "curve", x = 11.5, y = -25, xend = 12, yend = -14, 
           curvature = .2, arrow = arrow(length = unit(2, "mm")), colour = "white", size = 0.5
    )
firsts_gender1_graph
```

``` {r save}
# saving the plot

ggsave(firsts_gender1_graph, file="AA men and women.png", dpi=600,
       height=25, width=30, units="cm")
```